version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: development # for now, until I have good prod logging
      DATABASE_URL: "postgresql://${DB_USER-postgres}:${DB_PASSWORD-postgres}@localhost:5321/${DB_DATABASE-postgres}"

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER-postgres}"
      POSTGRES_DB: "{DB_DATABASE-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD-postgres}"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
